import React, { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout.jsx";
import Alert from "../components/Alert.jsx";
import Loader from "../components/Loader.jsx";
import api from "../api/axios.js";

export default function RoadmapPage() {
  const [roadmap, setRoadmap] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");

  const load = () => {
    setLoading(true);
    api
      .get("/roadmap")
      .then((res) => setRoadmap(res.data.hasRoadmap ? res.data.roadmap : null))
      .finally(() => setLoading(false));
  };

  useEffect(load, []);

  const handleGenerate = async () => {
    setGenerating(true);
    setError("");
    try {
      const res = await api.post("/roadmap/generate");
      setRoadmap(res.data.roadmap);
    } catch (err) {
      setError(err.response?.data?.message || "Could not generate roadmap.");
    } finally {
      setGenerating(false);
    }
  };

  if (loading) return (
    <AppLayout>
      <Loader />
    </AppLayout>
  );

  return (
    <AppLayout>
      <h1 className="text-2xl font-bold text-gray-900 mb-1">Personalized AI Roadmap</h1>
      <p className="text-sm text-gray-500 mb-6">A 4-week improvement plan generated by Gemini based on your weakest areas.</p>

      <Alert type="error" message={error} />

      <button className="btn-primary mb-6" onClick={handleGenerate} disabled={generating}>
        {generating ? "Generating with Gemini..." : roadmap ? "Regenerate Roadmap" : "Generate My Roadmap"}
      </button>

      {roadmap && (
        <div>
          {roadmap.weakAreas?.length > 0 && (
            <p className="text-sm text-gray-600 mb-4">
              Focus areas: <span className="font-medium text-gray-900">{roadmap.weakAreas.join(", ")}</span>
            </p>
          )}
          <p className="text-sm text-gray-600 mb-6">{roadmap.summary}</p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {roadmap.weeklyPlan?.map((week) => (
              <div key={week.week} className="card">
                <h3 className="font-semibold text-gray-900 mb-1">Week {week.week}: {week.focusArea}</h3>
                <ul className="list-disc list-inside text-sm text-gray-600 space-y-1 mt-2">
                  {week.tasks?.map((t, i) => <li key={i}>{t}</li>)}
                </ul>
              </div>
            ))}
          </div>
        </div>
      )}

      {!roadmap && !generating && (
        <p className="text-sm text-gray-400">No roadmap generated yet. Click the button above to get started.</p>
      )}
    </AppLayout>
  );
}
